### PR TITLE
Remove buffer limit recommendations

### PR DESCRIPTION
**Pull request by rachelleahklein**
The Telemetry SDK spec's recommendations on limits for the buffering of e.g. spans by number of items/amount of memory are just that: recommendations (i.e. **SHOULD**s). Perhaps for that reason, most language implementations have not yet imposed any limits on the amount of memory or the number of items that can be buffered between harvests.

I would like to propose that we consider removing this portion of the spec entirely. Users of the Telemetry SDKs have complete control over how many events are created and what the harvest interval is. Therefore, if they experience memory issues due to too many items being buffered between harvests, we should be able to advise them on how to change their approach or configuration to remediate it. Meanwhile, by not imposing limits, we can avoid a bit of complexity in the SDKs.

### CODE REVIEW

**Comment by carlo-808** [comment]
It looks like the Node agent does implement the 2000 item limit specified.  I'm guessing the reason for the limits is to be defensive about added memory usage.  Could we specify that the limits are optional or just recommendations?

**Comment by rachelleahklein** [comment]
Thanks for responding, @carlo-808. Sounds like you're proposing downloading this to "may" instead of "should."

I guess what I'm trying to ask is, _should_ we be defensive about memory limits in the SDK? Unlike in our agents, users of the SDK can choose shorter harvest intervals if the number of items buffered between harvests is a problem. It's also worth noting that a user could create so many items that they're still taking up too much memory even if we harvest as quickly as possible. In that case, limiting the number of items buffered between harvests has merely deferred the problem.

**Comment by justinfoote** [comment]
And the bigger problem I see is that, if we impose a limit, we probably need to specify what an SDK is supposed to do with new data points when it hits that limit, and this was a sticking point that we never resolved when we were first writing up these specs.

**Comment by rachelleahklein** [comment]
Yes, depending on what the SDKs would do when they hit their buffer limit, the amount of complexity we could avoid adding is potentially pretty significant.

**Comment by carlo-808** [comment]
This all makes sense to me.  Approving 👍

**Comment by vuqtran88** [comment]
The .Net Telemetry exporter currently doesn't implement the buffer limit in the event that it needs to retain data for later send. However, it will retry to the max number of times specified from the config before dropping the data to prevent memory growing issue. So this specs change makes sense.

**Comment by gfuller1** [comment]
The java telemetry sdk doesn't have limits currently so this is fine for us. I also would love to move away from having to explain limits to customers and accommodating special cases.

**Review by gfuller1 — APPROVED** [review]

**Comment by rachelleahklein** [comment]
Thanks everyone who has reviewed this so far!

@a-feld, any thoughts on this change from your team?

**Comment by a-feld** [comment]
No thoughts from Python, LGTM!

**Review by pyohannes — APPROVED** [review]
Looks good.

In the C (and Rust) Telemetry SDK, the user can specify a [limit of batches that can be queued](https://github.com/newrelic/newrelic-telemetry-sdk-c/blob/main/include/newrelic-telemetry-sdk.h#L414) at a time. This effectively prevents excessive memory usage.

**Comment by rachelleahklein** [comment]
With support across language implementations, I am merging this change. Thanks to all who reviewed and discussed!

**Pull request merged**
