### PR TITLE
doc: Added abiltiy to add additional headers to communication spec

### PR DESCRIPTION
**Pull request by carlosroman**
This is to provide specification to match this PR in the Golang SDK: https://github.com/newrelic/newrelic-telemetry-sdk-go/pull/27

### CODE REVIEW

**Comment by justinfoote** [comment]
For context: the infrastructure agent uses the go Telemetry SDK to send dimensional metrics to New Relic.  And the infra platform team has a requirement that the requests to the metrics API include the headers `Infra-Entity-Ids` and `Infra-Agent-Entity-Id`.  
We could add methods for each of these headers, but I think I'd prefer to future-proof it by requesting that Telemetry SDKs provide a mechanism to add arbitrary headers to all requests.  
@MrAlias @a-feld @purple4reina What do you think?

**Comment by a-feld** [comment]
Have we considered the corner cases around allowing arbitrary headers?

For example, what happens if duplicate headers are added? The [http spec](https://tools.ietf.org/html/rfc2616#section-4.2) more or less specifies that frameworks/servers may treat the values as comma separated values. What happens if these header names collide with what the SDK sends already? Can the collapsed header values become malformed?

I think generalizing is a good idea, but perhaps there's an alternate solution? For example, is there a way we can generalize the needs into a single-valued custom header like `X-Request-Metadata` with key/value pairs with a more defined specification (this could be a multi-value comma separated field, just as defined in the http/1.1 spec for example)?

**Comment by MrAlias** [comment]
> I think generalizing is a good idea, but perhaps there's an alternate solution? For example, is there a way we can generalize the needs into a single-valued custom header like `X-Request-Metadata` with key/value pairs with a more defined specification (this could be a multi-value comma separated field, just as defined in the http/1.1 spec for example)?

From my understanding of the ask, it seems like having all this sit under a single header name would not meet the requirements.

> For example, what happens if duplicate headers are added? The [http spec](https://tools.ietf.org/html/rfc2616#section-4.2) more or less specifies that frameworks/servers may treat the values as comma separated values. What happens if these header names collide with what the SDK sends already? Can the collapsed header values become malformed?

I think we could include information on how collision are handled here. Being explicit saying what should or should not override seems reasonable.

**Comment by carlosroman** [comment]
Thanks for the feedback, I shall update the spec with where the header processing in the chain should happen. The spec currently does not state a set of expected headers we should send. With this in mind I propose that this functionality sits post request creation (i.e. after HTTP request has been created) so that any headers the SDK sets can be overwritten. This includes changing the things such as the `Api-Key`.

The reason I suggest being able to change this is because I can see this as a potential way to run one instance of the telemetry SDK. It could change the API key based on the type of entity it sees coming through (if we could extend the store so that entities are batched/harvested by entity ID) sending the data to different accounts.

**Pull request closed without merging**
